apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: dev-cluster-tf-automation
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ../../../AWS/multi-env/iac/aws/dev
  sourceRef:
    kind: GitRepository
    name: flux-system
  runnerPodTemplate:
    spec:
      image: santonix/gitops-terraform:tf_az_cli_1_1
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_REGION




# apiVersion: infra.contrib.fluxcd.io/v1alpha2
# kind: Terraform
# metadata:
#   name: dev-cluster-tf-automation
#   namespace: flux-system
# spec:
#   interval: 1m
#   approvePlan: auto
#   destroyResourcesOnDeletion: true
#   path: ./AWS/multi-env/iac/aws/dev  # Adjust path if needed
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   runnerPodTemplate:
#     spec:
#       env:
#         - name: AWS_ACCESS_KEY_ID
#           valueFrom:
#             secretKeyRef:
#               name: aws-creds
#               key: AWS_ACCESS_KEY_ID
#         - name: AWS_SECRET_ACCESS_KEY
#           valueFrom:
#             secretKeyRef:
#               name: aws-creds
#               key: AWS_SECRET_ACCESS_KEY
#         - name: AWS_REGION
#           valueFrom:
#             secretKeyRef:
#               name: aws-creds
#               key: AWS_REGION
